apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gjenlevende-bs-sak-frontend
  namespace: etterlatte
spec:
  ingresses:
    - https://gjenlevende-bs.intern.dev.nav.no
    - https://gjenlevende-bs.ansatt.dev.nav.no
  image: {{ image }}
  port: 8080
  replicas:
    max: 1
    min: 1
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
      sidecar:
        autoLogin: true
