apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gjenlevende-bs-sak-frontend
  namespace: etterlatte
  labels:
    team: etterlatte

spec:
  # Applikasjon konfigurasjon
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  # Nettverk
  ingresses:
    - https://gjenlevende-bs.intern.dev.nav.no
    - https://gjenlevende-bs.ansatt.dev.nav.no

  # Helse
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5

  # Autentisering
  azure:
    application:
      enabled: true
      allowAllUsers: false
      replyURLs:
        - https://gjenlevende-bs.intern.dev.nav.no/oauth2/callback
      claims:
        groups:
          - id: ee5e0b5e-454c-4612-b931-1fe363df7c2c # 0000-GA-Enslig-Forsorger-Saksbehandler (MIDLERTIDLIG - for testing)
    sidecar:
      enabled: true
      autoLogin: true
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 50m

  accessPolicy:
    outbound:
      rules:
        - application: gjenlevende-bs-sak
